### ISSUE TITLE
Need a help

### ISSUE THREAD

**Issue by xiaoli26** [liangpan99/SamCon#3]
Thanks for sharing, I repeated the code and got the results. So excited!
Cuz I am a bachelor in this area, could anyone teach me how to delete the reference in the final demostration. 
And I would like to know how to repeat the former PD controllers as a control(Ctrl)?
Thx again!

**Comment by liangpan99** [comment]
**Q1: how to delete the reference in the final demostration**

https://github.com/liangpan99/SamCon/blob/ebd2f91d9a4b51f62f23e15b686c5f263eaf50f2/scripts/eval_samcon.py#L96-L105

To delete reference, a simple way is to modify the height value in the state variable **target_state**.

**Q2: how to repeat the former PD controllers as a control(Ctrl)?**
Sry, I dont understand this question, could you explain it a lot?

**Comment by xiaoli26** [comment]
> **Q1: how to delete the reference in the final demostration**
> 
> https://github.com/liangpan99/SamCon/blob/ebd2f91d9a4b51f62f23e15b686c5f263eaf50f2/scripts/eval_samcon.py#L96-L105
> 
> To delete reference, a simple way is to modify the height value in the state variable **target_state**.
> 
> **Q2: how to repeat the former PD controllers as a control(Ctrl)?** Sry, I dont understand this question, could you explain it a lot?

Thank you for ur answer!
I mean how to switch SamCon to PD controller, since it seems perfect by using the SamCon method, I wana see how it present by using the PD controller.

**Comment by liangpan99** [comment]
I see, set variable **action** equal to the rotation of internal joints in **target_state**.

https://github.com/liangpan99/SamCon/blob/ebd2f91d9a4b51f62f23e15b686c5f263eaf50f2/scripts/eval_samcon.py#L67-L81

Components of target_state: 
dim=3        global position of root joint
dim=4        global rotation of root joint
dim=Nx4    rotation of internal joints **_(set action to these values)_**
dim=3        linear velocity of root joint
dim=3        angular velocity of root joint
dim=Nx3    angular velocity of internal joints

https://github.com/liangpan99/SamCon/blob/f97844efdc82595eaeb4841776bf601d11fe67b3/envs/humanoid_stable_pd.py#L155-L165

**Comment by xiaoli26** [comment]
For the Question1 I modified here and it works.    
# visualize reconstructed motion
    vis_target_state = True   to   vis_target_state = False

**Comment by xiaoli26** [comment]
> I see, set variable **action** equal to the rotation of internal joints in **target_state**.
> 
> https://github.com/liangpan99/SamCon/blob/ebd2f91d9a4b51f62f23e15b686c5f263eaf50f2/scripts/eval_samcon.py#L67-L81
> 
> Components of target_state: dim=3 global position of root joint dim=4 global rotation of root joint dim=Nx4 rotation of internal joints **_(set action to these values)_** dim=3 linear velocity of root joint dim=3 angular velocity of root joint dim=Nx3 angular velocity of internal joints
> 
> https://github.com/liangpan99/SamCon/blob/f97844efdc82595eaeb4841776bf601d11fe67b3/envs/humanoid_stable_pd.py#L155-L165


Still confused about where to set the variable and where to edit in [humanoid_stable_pd.py]

**Comment by liangpan99** [comment]
Q1 你修改vis_target_state==False能work，是因为此时env._kin_agent的轨迹和env._sim_agent的轨迹一模一样，所以其实两者在可视化的时候是重合的，在少部分情况下，他们两个的轨迹会有些微小的差别，这时候再可视化的时候就会看出差异了。所以我建议还是手动给env._kin_agent.set_state(target_state) 里面的参数target_state加一个高度偏移量，比如-5，让kin agent位于地平面以下，这样可视化的时候就100%不会显示出来了

Q2 你修改action变量就行了，action里面的值其实就是关节转角，你如果把值设置为和reference motion一样的关节转角，得到的PD控制结果就是你想要的
for i in range(seq_len): 
     target_state = path['target_state'][i] 
     action = path['action'][i]  **# 改这里**
     env._kin_agent.set_state(target_state) 
     simulated_state, cost, _ = env.step(action) 
     simulated_states.append(simulated_state) 
     costs.append(cost)

你不需要修改humanoid_stable_pd.py，我放这部分的代码是为了告诉你state这个变量里面是怎么构成的。

**Comment by xiaoli26** [comment]
> Q1 你修改vis_target_state==False能work，是因为此时env._kin_agent的轨迹和env._sim_agent的轨迹一模一样，所以其实两者在可视化的时候是重合的，在少部分情况下，他们两个的轨迹会有些微小的差别，这时候再可视化的时候就会看出差异了。所以我建议还是手动给env._kin_agent.set_state(target_state) 里面的参数target_state加一个高度偏移量，比如-5，让kin agent位于地平面以下，这样可视化的时候就100%不会显示出来了
> 
> Q2 你修改action变量就行了，action里面的值其实就是关节转角，你如果把值设置为和reference motion一样的关节转角，得到的PD控制结果就是你想要的 for i in range(seq_len): target_state = path['target_state'][i] action = path['action'][i] **# 改这里** env._kin_agent.set_state(target_state) simulated_state, cost, _ = env.step(action) simulated_states.append(simulated_state) costs.append(cost)
> 
> 你不需要修改humanoid_stable_pd.py，我放这部分的代码是为了告诉你state这个变量里面是怎么构成的。

谢谢！刚刚也试出来了，非常详细和及时的解答，感谢！
